/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tarjetabancaria;

import java.awt.Color;
import javax.swing.JLabel;

/**
 *
 * @author Wilver
 */
public class panelCard extends javax.swing.JPanel {
    private String numeroTarjeta, nombreTitular, nombreBanco, nombreBanca, codigoCVV, fechaVigencia;
    private Color colorTarjeta, colorTexto;
    
    //4-Visa;  5-Master;  3-american
    /**
     * Creates new form NewJPanel
     */
    public panelCard() {
        initComponents();
        numeroTarjeta = lblNumeroTarjeta.getText();
        nombreTitular = lblNombreTitular.getText();
        nombreBanco = lblNombreBanco.getText();
        nombreBanca = lblBanca.getText();
        codigoCVV = lblCVV.getText();
        fechaVigencia = lblFechaVigencia.getText();
        
        colorTarjeta = lblTarjeta.getBackground();
        colorTexto= lblTarjeta.getForeground();
        
         lblVisa.setVisible(false);
         lblMastercard.setVisible(false);
         lblAmerican.setVisible(false);               
    }

    //Metodos accesores (getters)
    public String getNumeroTarjeta(){ numeroTarjeta = lblNumeroTarjeta.getText();    return numeroTarjeta; }
    public String getNombreTitular(){ nombreTitular = lblNombreTitular.getText(); return nombreTitular; }
    public String getNombreBanco(){ nombreBanco = lblNombreBanco.getText(); return nombreBanco;}
    public String getNombreBanca(){ nombreBanca = lblBanca.getText(); return nombreBanca;}
    public String getCodigoCVV(){ codigoCVV= lblCVV.getText(); return codigoCVV;}
    public String getFechaVigencia(){ fechaVigencia = lblFechaVigencia.getText();  return fechaVigencia; }
    
    public Color getColorTarjeta(){ colorTarjeta = lblTarjeta.getBackground(); return colorTarjeta;} //Color de fondo
    public Color getColorTexto(){ colorTexto = lblTarjeta.getForeground(); return colorTexto;} //Color de todos los textos
    
        
    //Metodos modificadores (setters)
    public void setNumeroTarjeta(String numero){ lblNumeroTarjeta.setText(numero);  }
    public void setNombreTitular(String nombreT){lblNombreTitular.setText(nombreT);}
    public void setNombreBanco(String nombreB){lblNombreBanco.setText(nombreB);}
    public void setNombreBanca(String bancaN){lblBanca.setText(bancaN);}
    public void setCodigoCVV(String cvv){ lblCVV.setText(cvv); }
    public void setFechaVigencia(String fecha){lblFechaVigencia.setText(fecha);}
    
    public void setColorTarjeta(Color color){ lblTarjeta.setBackground(color);}
    public void setColorTexto(Color color){
    lblTarjeta.setForeground(color);
    lblNumeroTarjeta.setForeground(color);
    lblNombreTitular.setForeground(color);
    lblNombreBanco.setForeground(color);
    lblBanca.setForeground(color);
    lblCVV.setForeground(color);
    lblFechaVigencia.setForeground(color);    
    lblVigencia.setForeground(color);
    lblCodigo.setForeground(color);
    }
    
    public void setVsibleVisa(boolean aFlag){ lblVisa.setVisible(aFlag); }
    public void setVisibleMastercard(boolean aFlag){ lblMastercard.setVisible(aFlag);}
    public void setVisibleAmerican(boolean aFlag){ lblAmerican.setVisible(aFlag);}
    
    //Metodos accesores a los propios elementos
    public JLabel getLblBanca(){ return lblBanca; }
    public JLabel getLblCVV(){ return lblCVV;}
    public JLabel getLblChip(){return lblChip;}
    public JLabel getLblCodigo(){ return lblCodigo;}
    public JLabel getLblFechaVigencia(){ return lblFechaVigencia; }
    public JLabel getLblNombreBanco(){ return lblNombreBanco; }
    public JLabel getLblNombreTitular (){ return lblNombreTitular; }
    public JLabel getLblNumeroTarjeta (){ return lblNumeroTarjeta;}
    public JLabel getLblTarjeta (){ return lblTarjeta;}
    public JLabel getLblVigencia (){ return lblVigencia;}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombreBanco = new javax.swing.JLabel();
        lblNumeroTarjeta = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        lblVigencia = new javax.swing.JLabel();
        lblFechaVigencia = new javax.swing.JLabel();
        lblCVV = new javax.swing.JLabel();
        lblNombreTitular = new javax.swing.JLabel();
        lblMastercard = new javax.swing.JLabel();
        lblChip = new javax.swing.JLabel();
        lblVisa = new javax.swing.JLabel();
        lblAmerican = new javax.swing.JLabel();
        lblBanca = new javax.swing.JLabel();
        lblTarjeta = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombreBanco.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        lblNombreBanco.setText("BBVA");
        add(lblNombreBanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        lblNumeroTarjeta.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        lblNumeroTarjeta.setText("0000 9999 000 9999");
        add(lblNumeroTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 250, -1));

        lblCodigo.setText("CVV");
        add(lblCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, -1, -1));

        lblVigencia.setText("Vigencia");
        add(lblVigencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        lblFechaVigencia.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        lblFechaVigencia.setText("01/2024");
        add(lblFechaVigencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        lblCVV.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        lblCVV.setText("000");
        add(lblCVV, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, -1, -1));

        lblNombreTitular.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        lblNombreTitular.setText("NOMBRE APELLIDO APELLIDO");
        add(lblNombreTitular, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 240, -1));

        lblMastercard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tarjetabancaria/imagen/mastercardlogo.png"))); // NOI18N
        add(lblMastercard, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));

        lblChip.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tarjetabancaria/imagen/chip2.png"))); // NOI18N
        lblChip.setText("chip");
        add(lblChip, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 50, 40));

        lblVisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tarjetabancaria/imagen/visalogo.png"))); // NOI18N
        add(lblVisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 70, 30));

        lblAmerican.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tarjetabancaria/imagen/americanexpreslogo.png"))); // NOI18N
        add(lblAmerican, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));
        add(lblBanca, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 70, 30));

        lblTarjeta.setBackground(java.awt.Color.orange);
        lblTarjeta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblTarjeta.setOpaque(true);
        add(lblTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 180));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAmerican;
    private javax.swing.JLabel lblBanca;
    private javax.swing.JLabel lblCVV;
    private javax.swing.JLabel lblChip;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblFechaVigencia;
    private javax.swing.JLabel lblMastercard;
    private javax.swing.JLabel lblNombreBanco;
    private javax.swing.JLabel lblNombreTitular;
    private javax.swing.JLabel lblNumeroTarjeta;
    private javax.swing.JLabel lblTarjeta;
    private javax.swing.JLabel lblVigencia;
    private javax.swing.JLabel lblVisa;
    // End of variables declaration//GEN-END:variables
}
